# Generated by Django 6.0.3 on 2026-04-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_supplier_medicine_cost_price_and_more'),
    ]

    operations = [
    ]
